[package]
name = "eval_string"
version = "0.1.0"
authors = ["Dave98-dev <71784042+Dave98-dev@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
